### ISSUE TITLE
Types not found

### ISSUE THREAD

**Issue by Brighton-OHTech** [Allmacamo/react-native-payfast-checkout#10]
Figured the issue if caused by the file type `types.d.ts`. Renaming the file to `types.ts` fixes the issue.

**Comment by Allmacamo** [comment]
Hi @Brighton-OHTech  thanks for the above. I will look into and release a fix.

**Comment by Kaivan30** [comment]
@Allmacamo Hi, still bug not resolve?

**Comment by Allmacamo** [comment]
@Brighton-OHTech  @Kaivan30  sorry for the delay please see Pull Request https://github.com/Allmacamo/react-native-payfast-checkout/pull/11
